config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/home', to: 'sessions#home'
  post '/pick', to: 'sessions#pick'
  get '/wishlist', to: 'sessions#wishlist'
  post '/wishlist/match', to: 'sessions#match_wishlist'

  get '/admin', to: 'admin#check'
  get '/admin/login', to: 'admin#new'
  post '/admin/login', to: 'admin#create'

  get '/admin/user/:id/confirm', to: 'admin/users#confirm', as: "confirm_admin_user"

  post '/items/:id/back', to: 'items#back_row', as: "back_row"
  resources :items, except: [:show, :index] do
    member do
      post :edit_row
    end
  end

  namespace :admin do
    resources :users
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  
  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, on: :create, presence: true, length: { minimum: 4}
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]
  before_action :set_last_page, only: [:new, :edit]
  before_action :require_admin
  layout "admin"

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = "User was successfully created."
      if params[:commit] == "Create and add another"
        redirect_to new_admin_user_path
      else
        redirect_to admin_path
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    
    if @user.update(user_params)
      flash[:notice] = "User was successfully updated."
      redirect_to admin_path
    else
      render :edit
    end
  end

  def confirm
  end

  def destroy
    @user.destroy
    flash[:notice] = "User was successfully deleted."
    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password, :matched, :matched_id, :role)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def set_last_page
      session[:last_page] = request.env["HTTP_REFERER"]
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin, except: [:check, :new, :create]
  layout "admin"

  def new
  end

  def create
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password]) && @user.role == "admin"
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully logged in."
      redirect_to admin_path
    else
      flash[:error] = "Your username or password was incorrect."
      redirect_to admin_login_path
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to root_path
  end

  def check
    if !logged_in?
      redirect_to admin_login_path
    elsif !admin?
      flash[:notice] = "You are not allowed to do that."
      redirect_to root_path
    else
      redirect_to admin_users_path
    end
  end

  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :admin?, :access_denied, :require_admin

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def admin?
    current_user.role == "admin"
  end

  def access_denied
    flash[:error] = "You are not allowed to do that."
    redirect_to root_path
  end

  def require_admin
    access_denied unless logged_in? and admin?
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, except: [:new, :create]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    current_user.items << @item

    if @item.save
      redirect_to "/wishlist"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to "/wishlist"
    else
      render :edit
    end
  end

  def edit_row
    respond_to do |format|
      format.js {}
    end
  end

  def back_row
    respond_to do |format|
      format.js {}
    end
  end

  def edit_name
    respond_to do |format|
      format.js {}
    end
  end

  def edit_link
    respond_to do |format|
      format.js {}
    end
  end


  def destroy
    @item.destroy
    flash[:notice] = "Wishlist item was successfully deleted."
    redirect_to "/wishlist"
  end

  private
    def item_params
      params.require(:item).permit(:name, :link)
    end

    def set_item
      @item = Item.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user, only: [:home, :destroy, :wishlist, :match_wishlist]
  layout "application"

  def home
    @match = User.find(current_user.matched_id) if current_user.matched
  end

  def new
    if logged_in?
      redirect_to home_path
    end
  end

  def create
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/home'
    else
      flash[:error] = "Your username or password was incorrect."
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to root_path
  end

  def wishlist
    @item = Item.new
  end

  def match_wishlist 
    @match = User.find(current_user.matched_id) if current_user.matched
    @show = params[:show]
    respond_to do |format|
      format.js {}
    end
  end

  def pick
    pick_user
    @match = User.find(current_user.matched_id) if current_user.matched

    respond_to do |format|
      format.js {}
    end
  end

  private
    def require_user
      if !logged_in?
        flash[:error] = "You must be logged in to do that."
        redirect_to root_path
      end
    end

    def picked_users
      users = User.all
      picked_users = []

      users.each do |user|
        picked_users << user.matched_id if (user.matched_id != 0 || user.matched_id != nil)
      end

      picked_users
    end

    def pick_user
      users = User.all
      user_arr = []
      match = 0

      users.each do |user|
        if !(picked_users.include?(user.id))
          user_arr << user.id
          puts user_arr
        end
      end

      begin
        match = user_arr.sample
      end until (match != current_user.id)

      current_user.matched = true
      current_user.matched_id = match

      current_user.save

    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_url(str)
    if (str.starts_with?('http://') || str.starts_with?('https://')) && str.include?(".com")
      str
    elsif !str.include?(".com")
      "http://#{str}.com"
    else
      "http://#{str}"
    end
  end
end

app/views/admin/_login_form.html.erb
<%= form_tag '/admin/login' do %>
  <div class="form-group">
    <%= text_field_tag :username, nil, placeholder: "Username", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= password_field_tag :password, nil, placeholder: "Password", class: "form-control" %>
  </div>

  <%= submit_tag "Login", class: "btn btn-primary" %>
<% end %>

app/views/admin/_sidenav.html.erb
<ul>Manage
  <li>Users</li>
</ul>

app/views/admin/new.html.erb
<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <div class="nobg-form-container">
      <div class="black-form-header">
        <span>Admin</span>
      </div>
      <div class="form-body">
        <%= render 'login_form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], html: {class: 'form-horizontal'} do |f| %>
  <%= render "layouts/errors", object: @user %>
  <div class="form-group">
    <%= f.label :first_name, class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :username, class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :role, class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :role, placeholder: "Role", class: "form-control" %>
    </div>
  </div>
  
  <%= f.submit @user.new_record? ? "Create" : "Update", class: "btn btn-primary" %>
  <% if @user.new_record? %>
    <%= f.submit "Create and add another", class: "btn btn-info" %>
  <% end %>
  <%= link_to "Back", admin_users_path, class: "btn btn-default" %>
<% end %>

app/views/admin/users/confirm.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h3>Confirm Delete</h3>
    <p>You are about to delete the following user:</p>
    <p><strong><%= @user.username %></strong></p>
    <p>Are you sure?</p>
    <br/>
    <%= link_to "Yes, I am sure", admin_user_path(@user), method: "delete", action: "destroy", class: "btn btn-danger" %>
    <%= link_to "Cancel", admin_users_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="form-header">
      <span>Edit User</span>
    </div>
    <div class="form-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>All Users (<%= @users.size %>)</h3>
    <table class="table">
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Username</th>
        <th>Role</th>
        <th>Matched</th>
        <th>Actions</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.username %></td>
          <td><%= user.role %></td>
          <td><%= user.matched %></td>
          <td>
            <%= link_to edit_admin_user_path(user) do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
            <%= link_to admin_user_path(user) do %>
              <span class="glyphicon glyphicon-eye-open"></span>
            <% end %>
            <%= link_to confirm_admin_user_path(user) do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="nobg-form-container">
      <div class="black-form-header">
        <span>Create User</span>
      </div>
      <div class="form-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/items/_edit_form.html.haml
= form_for @item do |f|
  .col-md-5
    = f.text_field :name, class: "form-control"
  .col-md-5
    = f.text_field :link, class: "form-control"
  .col-md-2.text-right
    = button_tag type: "submit", method: "post", remote: true, class: "btn btn-success" do
      %span.glyphicon.glyphicon-ok
    = link_to back_row_path(@item), method: "post", remote: true, class: "btn btn-default" do
      %span.glyphicon.glyphicon-chevron-left

app/views/items/_edit_name_form.html.haml
= form_for @item do |f|
  .name
    .input-group
      = f.text_field :name, class: "form-control"
      %span.input-group-btn
        = button_tag type: "submit", class: "btn btn-success" do
          %span.glyphicon.glyphicon-ok

app/views/items/_item_row.html.haml
.name.col-md-5= @item.name
.link.col-md-5
  = link_to "Go to Item's Link", full_url(@item.link) if !@item.link.empty?
.actions.col-md-2.text-right
  = link_to edit_row_item_path(@item), method: "post", remote: true, class: "btn btn-warning" do
    %span.glyphicon.glyphicon-pencil
  = link_to item_path(@item), method: "delete", action: "destroy", data: {confirm: "Deleting item, Are you sure?"}, class: "btn btn-danger" do
    %span.glyphicon.glyphicon-remove

app/views/items/back_row.js.erb
$("#item-<%= @item.id %>").html("<%= escape_javascript(render 'item_row') %>")

app/views/items/edit_row.js.erb
$("#item-<%= @item.id %>").html("<%= escape_javascript(render 'edit_form') %>")

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div class="alert alert-danger">
  <h5>The following errors occurred: </h5>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Admin Dashboard</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to 'All Users', admin_users_path %>
            </li>
            <li>
              <%= link_to "Add New", new_admin_user_path %>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/logout">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html class="admin">
  <head>
    <title>Secret Santa</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

  </head>
  <body>
    <header>
      <%= render "layouts/navbar" if logged_in? %>
    </header>

    <div class="messages">
      <%= render "layouts/message" %>
    </div>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret Santa</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    
    <div class="welcome-banner">
      <span>Family Secret Santa!</span>
    </div>

    <div class="messages">
      <%= render "layouts/message" %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>